version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Resume-API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s26abkhsecs4"
s3_prefix = "Resume-API"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
